baseURL = "https://jackburkhardt.com/"
languageCode = "en-us"
title = "jack burkhardt"
theme = "archie"
copyright = "© Jack Burkhardt"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="dark" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Site is still under construction. Check back later."

# Social Tags

[[params.social]]
name = "github"
icon = "github"
url = "https://github.com/jackburkhardt"

[[params.social]]
name = "envelope"
icon = "envelope"
url = "mailto:mail@jackburkhardt.com"

# Main menu Items

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "resume"
url = "/resume/resume-spr21.pdf"
weight = 4