baseURL: "https://jackburkhardt.com/"
title: jack burkhardt
paginate: 7
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: jack burkhardt
  description: "My personal website."
  keywords: [Blog, Portfolio]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Jack Burkhardt"
    icon: ""
    iconHeight: 35

  homeInfoParams:
    title: "Hi, I'm Jack."
    content: "I am an undergraduate student studying Computer Science at Northwestern University. My interests lie generally in interactive entertainment, sociology, and human-computer interaction. For more info about me, see my [about page](https://jackburkhardt.com/about/) or some featured projects below!"

  # profile-mode
#  profileMode:
 #   enabled: false # needs to be explicitly set
 #   title: ExampleSite
 #   subtitle: "This is subtitle"
 #   imageUrl: "<img location>"
  #  imageWidth: 120
 #   imageHeight: 120
  #  imageTitle: my image
 #   buttons:
 #     - name: Posts
  #      url: posts
  #    - name: Tags
  #      url: tags

  socialIcons:
    - name: email
      url: "mailto:hello@jackburkhardt.com"
    - name: github
      url: "https://github.com/jackburkhardt"
    - name: twitch
      url: "https://twitch.tv/12point5"
    - name: linkedin
      url: "https://linkedin.com/in/jack-burkhardt"
    - name: itchio
      url: "https://jackburkhardt.itch.io/"

#  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"
#    bing:
#      SiteVerificationTag: "XYZabc"
#   yandex:
#      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/jackburkhardt/site/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: about
      name: about
      url: /about/
      weight: 30
    - identifier: projects
      name: projects
      url: /projects/
      weight: 30
    - identifier: blog
      name: blog
      url: /blog/
      weight: 40
    - identifier: resume
      name: resume
      url: /resume/jack-burkhardt-resume-fa22.pdf
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai